const localeData = window._discourse_locale_data ??= {};
localeData.messageFormatData = function (messageFormatModules) {
  const { number, plural, select } = messageFormatModules["@messageformat/runtime"];
  const { en, zh } = messageFormatModules["@messageformat/runtime/lib/cardinals"];
  return {
    "zh-CN": {
      "about.traffic_info_footer_MF": (d) => "在过去 6 个月内，此网站每月向约 " + plural(d.total_visitors, 0, zh, { other: number("zh-CN", d.total_visitors, 0) + " 人" }) + "提供内容，其中约 " + plural(d.eu_visitors, 0, zh, { other: number("zh-CN", d.eu_visitors, 0) + " 人" }) + "来自欧盟。\n",
      "about.activities.visitors_MF": (d) => plural(d.total_count, 0, zh, { other: d.total_formatted_number + " 位访客" }) + "，约 " + plural(d.eu_count, 0, zh, { other: d.eu_formatted_number }) + " 人来自欧盟\n",
      "user.messages.read_more_group_pm_MF": (d) => select(d.HAS_UNREAD_AND_NEW, { true: "\n    " + plural(d.UNREAD, 0, zh, { "0": "", other: "还有 <a href=\"" + d.basePath + "/u/" + d.username + "/messages/group/" + d.groupName + "/unread\">" + number("zh-CN", d.UNREAD, 0) + " 条未读</a>" }) + "\n    " + plural(d.NEW, 0, zh, { "0": "", other: "和 <a href=\"" + d.basePath + "/u/" + d.username + "/messages/group/" + d.groupName + "/new\">" + number("zh-CN", d.NEW, 0) + " 条新</a>消息，或浏览 " + d.groupLink + " 中的其他消息" }) + "\n  ", false: "\n    " + plural(d.UNREAD, 0, zh, { "0": "", other: "还有 <a href=\"" + d.basePath + "/u/" + d.username + "/messages/group/" + d.groupName + "/unread\">" + number("zh-CN", d.UNREAD, 0) + " 条未读</a>消息，或浏览 " + d.groupLink + " 中的其他消息" }) + "\n    " + plural(d.NEW, 0, zh, { "0": "", other: "还有 <a href=\"" + d.basePath + "/u/" + d.username + "/messages/group/" + d.groupName + "/new\">" + number("zh-CN", d.NEW, 0) + " 条新</a>消息，或浏览 " + d.groupLink + " 中的其他消息" }) + "\n  ", other: "" }) + "\n",
      "user.messages.read_more_personal_pm_MF": (d) => select(d.HAS_UNREAD_AND_NEW, { true: "\n    " + plural(d.UNREAD, 0, zh, { "0": "", other: "还有 <a href=\"" + d.basePath + "/u/" + d.username + "/messages/unread\">" + number("zh-CN", d.UNREAD, 0) + " 条未读</a>" }) + "\n    " + plural(d.NEW, 0, zh, { "0": "", other: "和 <a href=\"" + d.basePath + "/u/" + d.username + "/messages/new\">" + number("zh-CN", d.NEW, 0) + " 条新</a>消息，或者浏览其他<a href=\"" + d.basePath + "/u/" + d.username + "/messages\">个人消息</a>" }) + "\n  ", false: "\n    " + plural(d.UNREAD, 0, zh, { "0": "", other: "还有 <a href=\"" + d.basePath + "/u/" + d.username + "/messages/unread\">" + number("zh-CN", d.UNREAD, 0) + " 条未读</a>消息，或者浏览其他<a href=\"" + d.basePath + "/u/" + d.username + "/messages\">个人消息</a>" }) + "\n    " + plural(d.NEW, 0, zh, { "0": "", other: "还有 <a href=\"" + d.basePath + "/u/" + d.username + "/messages/new\">" + number("zh-CN", d.NEW, 0) + " 条新</a>消息，或者浏览其他<a href=\"" + d.basePath + "/u/" + d.username + "/messages\">个人消息</a>" }) + "\n  ", other: "" }) + "\n",
      "user.invited.invite.link_validity_MF": (d) => "链接最多可用于 " + plural(d.user_count, 0, zh, { other: number("zh-CN", d.user_count, 0) + " 个用户" }) + "，并且将在 " + plural(d.duration_days, 0, zh, { other: number("zh-CN", d.duration_days, 0) + " 天" }) + "后到期。\n",
      "logs_error_rate_notice.reached_hour_MF": (d) => "<b>" + d.relativeAge + "</b> – <a href=\"" + d.url + "\" target=\"_blank\">" + plural(d.rate, 0, zh, { other: number("zh-CN", d.rate, 0) + " 个错误/小时" }) + "</a>达到了 " + plural(d.limit, 0, zh, { other: number("zh-CN", d.limit, 0) + " 个错误/小时" }) + "的站点设置上限。\n",
      "logs_error_rate_notice.reached_minute_MF": (d) => "<b>" + d.relativeAge + "</b> – <a href=\"" + d.url + "\" target=\"_blank\">" + plural(d.rate, 0, zh, { other: number("zh-CN", d.rate, 0) + " 个错误/分钟" }) + "</a>达到了 " + plural(d.limit, 0, zh, { other: number("zh-CN", d.limit, 0) + " 个错误/分钟" }) + "的站点设置上限。\n",
      "logs_error_rate_notice.exceeded_hour_MF": (d) => "<b>" + d.relativeAge + "</b> – <a href=\"" + d.url + "\" target=\"_blank\">" + plural(d.rate, 0, zh, { other: number("zh-CN", d.rate, 0) + " 个错误/小时" }) + "</a>超过了 " + plural(d.limit, 0, zh, { other: number("zh-CN", d.limit, 0) + " 个错误/小时" }) + "的站点设置上限。\n",
      "logs_error_rate_notice.exceeded_minute_MF": (d) => "<b>" + d.relativeAge + "</b> – <a href=\"" + d.url + "\" target=\"_blank\">" + plural(d.rate, 0, zh, { other: " " + number("zh-CN", d.rate, 0) + " 个错误每分钟" }) + "</a>超过了 " + plural(d.limit, 0, zh, { other: " " + number("zh-CN", d.limit, 0) + " 个错误/分钟" }) + "的站点设置上限。\n",
      "summary.description_time_MF": (d) => "有 " + plural(d.replyCount, 0, zh, { other: "<b>" + number("zh-CN", d.replyCount, 0) + "</b> 个回复" }) + "，预计阅读时间为 <b>" + plural(d.readingTime, 0, zh, { other: number("zh-CN", d.readingTime, 0) + " 分钟" }) + "</b>。\n",
      "topic.read_more_MF": (d) => select(d.HAS_UNREAD_AND_NEW, { true: "\n    " + plural(d.UNREAD, 0, zh, { "0": "", other: "<a href=\"" + d.unreadUrl + "\">" + number("zh-CN", d.UNREAD, 0) + " 个未读</a>话题" }) + "\n    " + plural(d.NEW, 0, zh, { "0": "", other: "以及剩余 <a href=\"" + d.newUrl + "\">" + number("zh-CN", d.NEW, 0) + " 个新</a>话题，" }) + "\n  ", false: "\n    " + plural(d.UNREAD, 0, zh, { "0": "", other: "剩余 <a href=\"" + d.unreadUrl + "\">" + number("zh-CN", d.UNREAD, 0) + " 个未读</a>话题，" }) + "\n    " + plural(d.NEW, 0, zh, { "0": "", other: "剩余 <a href=\"" + d.newUrl + "\">" + number("zh-CN", d.NEW, 0) + " 个新</a>话题，" }) + "\n  ", other: "" }) + "\n" + select(d.HAS_CATEGORY, { true: "或者浏览" + d.categoryLink + "中的其他话题", false: "或者<a href=\"" + d.basePath + "/latest\">查看最新话题</a>", other: "" }) + "\n",
      "flagging.delete_confirm_MF": (d) => "您将删除此用户的 " + plural(d.POSTS, 0, zh, { other: "<b>" + number("zh-CN", d.POSTS, 0) + "</b> 个帖子" }) + "和 " + plural(d.TOPICS, 0, zh, { other: "<b>" + number("zh-CN", d.TOPICS, 0) + "</b> 个话题" }) + "，移除他们的帐户，禁止其 IP 地址 <b>" + d.ip_address + "</b> 再次注册，同时将其电子邮件地址 <b>" + d.email + "</b> 加入永久屏蔽名单。确定此用户是垃圾信息发布者吗？\n",
      posts_likes_MF: (d) => plural(d.count, 0, zh, { other: number("zh-CN", d.count, 0) + " 条回复，" }) + select(d.ratio, { low: "点赞率高，", med: "点赞率非常高，", high: "点赞率极高，", other: "" }) + "跳到第一个或最后一个帖子…\n",
      "chat.mention_warning.groups.too_many_members_MF": (d) => plural(d.groupCount, 0, zh, { "1": "\n          " + select(d.isAdmin, { true: "\n              " + plural(d.notificationLimit, 0, zh, { other: "提及 @" + d.group1 + " 超出了 " + number("zh-CN", d.notificationLimit, 0) + " 个用户的<a href=\"" + d.siteSettingUrl + "\" target=\"_blank\">通知限制</a>。" }) + "\n            ", false: "\n              " + plural(d.notificationLimit, 0, zh, { other: "提及 @" + d.group1 + " 超出了 " + number("zh-CN", d.notificationLimit, 0) + " 个用户的通知限制。" }) + "\n            ", other: "" }) + "\n        ", "2": "\n          " + select(d.isAdmin, { true: "\n              " + plural(d.notificationLimit, 0, zh, { other: "提及 @" + d.group1 + " 和 @" + d.group2 + " 超出了 " + number("zh-CN", d.notificationLimit, 0) + " 个用户的<a href=\"" + d.siteSettingUrl + "\" target=\"_blank\">通知限制</a>。" }) + "\n            ", false: "\n              " + plural(d.notificationLimit, 0, zh, { other: "提及 @" + d.group1 + " 和 @" + d.group2 + " 超出了 " + number("zh-CN", d.notificationLimit, 0) + " 个用户的通知限制。" }) + "\n            ", other: "" }) + "\n        ", other: "\n          " + select(d.isAdmin, { true: "\n              " + plural(d.notificationLimit, 0, zh, { other: "提及这 " + d.groupCount + " 个群组超出了 " + number("zh-CN", d.notificationLimit, 0) + " 个用户的<a href=\"" + d.siteSettingUrl + "\" target=\"_blank\">通知限制</a>。" }) + "\n            ", false: "\n              " + plural(d.notificationLimit, 0, zh, { other: "提及这 " + d.groupCount + " 个群组超出了 " + number("zh-CN", d.notificationLimit, 0) + " 个用户的通知限制。" }) + "\n            ", other: "" }) + "\n        " }) + "\n",
      "chat.create_channel.auto_join_users.warning_multiple_groups_MF": (d) => plural(d.groupCount, 0, zh, { other: "\n          " + plural(d.userCount, 0, zh, { other: "是否自动添加 " + d.userCount + " 个来自 " + d.groupName + " 和其他 " + d.groupCount + " 个群组的用户？" }) + "\n        " }) + "\n",
      "discourse_rewind.reports.chat_usage.message_2_MF": (d) => "您有包含 " + plural(d.channel_count, 0, zh, { other: "<strong>" + number("zh-CN", d.channel_count, 0) + "</strong> 个人或群组" }) + "的" + plural(d.dm_count, 0, zh, { other: "<strong>" + number("zh-CN", d.dm_count, 0) + "</strong> DM 对话" }) + "。\n",
      "admin.user.penalty_post_delete_all_confirmation_MF": (d) => "<span>这将删除 \n" + plural(d.TOPICS, 0, zh, { other: number("zh-CN", d.TOPICS, 0) + " 个话题" }) + "和 \n" + plural(d.REPLIES, 0, zh, { other: number("zh-CN", d.REPLIES, 0) + " 条回复" }) + "。<b>此操作无法撤消</b>！确定要执行此操作吗？</span>\n",
      "admin.user.penalty_history_MF": (d) => "在过去 6 个月中，此用户被<b>封禁 " + plural(d.SUSPENDED, 0, zh, { other: number("zh-CN", d.SUSPENDED, 0) + " 次" }) + "</b>，被<b>禁言 " + plural(d.SILENCED, 0, zh, { other: number("zh-CN", d.SILENCED, 0) + " 次" }) + "</b>。",
      "admin.user.delete_all_posts_confirm_MF": (d) => "您将删除 " + plural(d.POSTS, 0, zh, { other: number("zh-CN", d.POSTS, 0) + " 个帖子" }) + "和 " + plural(d.TOPICS, 0, zh, { other: number("zh-CN", d.TOPICS, 0) + " 个话题" }) + "。确定吗？\n"
    },
    en: {
      "about.traffic_info_footer_MF": (d) => "In the last 6 months, this site has served content to an estimated " + plural(d.total_visitors, 0, en, { one: number("en", d.total_visitors, 0) + " people", other: number("en", d.total_visitors, 0) + " people" }) + " each month, with an estimated " + plural(d.eu_visitors, 0, en, { one: number("en", d.eu_visitors, 0) + " people", other: number("en", d.eu_visitors, 0) + " people" }) + " from the European Union.\n",
      "about.activities.visitors_MF": (d) => plural(d.total_count, 0, en, { one: d.total_formatted_number + " visitor", other: d.total_formatted_number + " visitors" }) + ", about " + plural(d.eu_count, 0, en, { one: d.eu_formatted_number, other: d.eu_formatted_number }) + " from the EU\n",
      "user.messages.read_more_group_pm_MF": (d) => select(d.HAS_UNREAD_AND_NEW, { true: "\n    " + plural(d.UNREAD, 0, en, { "0": "", one: "There is <a href=\"" + d.basePath + "/u/" + d.username + "/messages/group/" + d.groupName + "/unread\">" + number("en", d.UNREAD, 0) + " unread</a>", other: "There are <a href=\"" + d.basePath + "/u/" + d.username + "/messages/group/" + d.groupName + "/unread\">" + number("en", d.UNREAD, 0) + " unread</a>" }) + "\n    " + plural(d.NEW, 0, en, { "0": "", one: " and <a href=\"" + d.basePath + "/u/" + d.username + "/messages/group/" + d.groupName + "/new\">" + number("en", d.NEW, 0) + " new</a> message remaining, or browse other messages in " + d.groupLink, other: " and <a href=\"" + d.basePath + "/u/" + d.username + "/messages/group/" + d.groupName + "/new\">" + number("en", d.NEW, 0) + " new</a> messages remaining, or browse other messages in " + d.groupLink }) + "\n  ", false: "\n    " + plural(d.UNREAD, 0, en, { "0": "", one: "There is <a href=\"" + d.basePath + "/u/" + d.username + "/messages/group/" + d.groupName + "/unread\">" + number("en", d.UNREAD, 0) + " unread</a> message remaining, or browse other messages in " + d.groupLink, other: "There are <a href=\"" + d.basePath + "/u/" + d.username + "/messages/group/" + d.groupName + "/unread\">" + number("en", d.UNREAD, 0) + " unread</a> messages remaining, or browse other messages in " + d.groupLink }) + "\n    " + plural(d.NEW, 0, en, { "0": "", one: "There is <a href=\"" + d.basePath + "/u/" + d.username + "/messages/group/" + d.groupName + "/new\">" + number("en", d.NEW, 0) + " new</a> message remaining, or browse other messages in " + d.groupLink, other: "There are <a href=\"" + d.basePath + "/u/" + d.username + "/messages/group/" + d.groupName + "/new\">" + number("en", d.NEW, 0) + " new</a> messages remaining, or browse other messages in " + d.groupLink }) + "\n  ", other: "" }) + "\n",
      "user.messages.read_more_personal_pm_MF": (d) => select(d.HAS_UNREAD_AND_NEW, { true: "\n    " + plural(d.UNREAD, 0, en, { "0": "", one: "There is <a href=\"" + d.basePath + "/u/" + d.username + "/messages/unread\">" + number("en", d.UNREAD, 0) + " unread</a>", other: "There are <a href=\"" + d.basePath + "/u/" + d.username + "/messages/unread\">" + number("en", d.UNREAD, 0) + " unread</a>" }) + "\n    " + plural(d.NEW, 0, en, { "0": "", one: " and <a href=\"" + d.basePath + "/u/" + d.username + "/messages/new\">" + number("en", d.NEW, 0) + " new</a> message remaining, or browse other <a href=\"" + d.basePath + "/u/" + d.username + "/messages\">personal messages</a>", other: " and <a href=\"" + d.basePath + "/u/" + d.username + "/messages/new\">" + number("en", d.NEW, 0) + " new</a> messages remaining, or browse other <a href=\"" + d.basePath + "/u/" + d.username + "/messages\">personal messages</a>" }) + "\n  ", false: "\n    " + plural(d.UNREAD, 0, en, { "0": "", one: "There is <a href=\"" + d.basePath + "/u/" + d.username + "/messages/unread\">" + number("en", d.UNREAD, 0) + " unread</a> message remaining, or browse other <a href=\"" + d.basePath + "/u/" + d.username + "/messages\">personal messages</a>", other: "There are <a href=\"" + d.basePath + "/u/" + d.username + "/messages/unread\">" + number("en", d.UNREAD, 0) + " unread</a> messages remaining, or browse other <a href=\"" + d.basePath + "/u/" + d.username + "/messages\">personal messages</a>" }) + "\n    " + plural(d.NEW, 0, en, { "0": "", one: "There is <a href=\"" + d.basePath + "/u/" + d.username + "/messages/new\">" + number("en", d.NEW, 0) + " new</a> message remaining, or browse other <a href=\"" + d.basePath + "/u/" + d.username + "/messages\">personal messages</a>", other: "There are <a href=\"" + d.basePath + "/u/" + d.username + "/messages/new\">" + number("en", d.NEW, 0) + " new</a> messages remaining, or browse other <a href=\"" + d.basePath + "/u/" + d.username + "/messages\">personal messages</a>" }) + "\n  ", other: "" }) + "\n",
      "user.invited.invite.link_validity_MF": (d) => "Link is valid for up to " + plural(d.user_count, 0, en, { one: number("en", d.user_count, 0) + " user", other: number("en", d.user_count, 0) + " users" }) + " and expires in " + plural(d.duration_days, 0, en, { one: number("en", d.duration_days, 0) + " day", other: number("en", d.duration_days, 0) + " days" }) + ".\n",
      "logs_error_rate_notice.reached_hour_MF": (d) => "<b>" + d.relativeAge + "</b> – <a href=\"" + d.url + "\" target=\"_blank\">" + plural(d.rate, 0, en, { one: number("en", d.rate, 0) + " error/hour", other: number("en", d.rate, 0) + " errors/hour" }) + "</a> reached site setting limit of " + plural(d.limit, 0, en, { one: number("en", d.limit, 0) + " error/hour", other: number("en", d.limit, 0) + " errors/hour" }) + ".\n",
      "logs_error_rate_notice.reached_minute_MF": (d) => "<b>" + d.relativeAge + "</b> – <a href=\"" + d.url + "\" target=\"_blank\">" + plural(d.rate, 0, en, { one: number("en", d.rate, 0) + " error/minute", other: number("en", d.rate, 0) + " errors/minute" }) + "</a> reached site setting limit of " + plural(d.limit, 0, en, { one: number("en", d.limit, 0) + " error/minute", other: number("en", d.limit, 0) + " errors/minute" }) + ".\n",
      "logs_error_rate_notice.exceeded_hour_MF": (d) => "<b>" + d.relativeAge + "</b> – <a href=\"" + d.url + "\" target=\"_blank\">" + plural(d.rate, 0, en, { one: number("en", d.rate, 0) + " error/hour", other: number("en", d.rate, 0) + " errors/hour" }) + "</a> exceeded site setting limit of " + plural(d.limit, 0, en, { one: number("en", d.limit, 0) + " error/hour", other: number("en", d.limit, 0) + " errors/hour" }) + ".\n",
      "logs_error_rate_notice.exceeded_minute_MF": (d) => "<b>" + d.relativeAge + "</b> – <a href=\"" + d.url + "\" target=\"_blank\">" + plural(d.rate, 0, en, { one: number("en", d.rate, 0) + " error/minute", other: number("en", d.rate, 0) + " errors/minute" }) + "</a> exceeded site setting limit of " + plural(d.limit, 0, en, { one: number("en", d.limit, 0) + " error/minute", other: number("en", d.limit, 0) + " errors/minute" }) + ".\n",
      "summary.description_time_MF": (d) => "There " + plural(d.replyCount, 0, en, { one: "is <b>" + number("en", d.replyCount, 0) + "</b> reply", other: "are <b>" + number("en", d.replyCount, 0) + "</b> replies" }) + " with an estimated read time of <b>" + plural(d.readingTime, 0, en, { one: number("en", d.readingTime, 0) + " minute", other: number("en", d.readingTime, 0) + " minutes" }) + "</b>.\n",
      "topic.read_more_MF": (d) => select(d.HAS_UNREAD_AND_NEW, { true: "\n    " + plural(d.UNREAD, 0, en, { "0": "", one: "There is <a href=\"" + d.unreadUrl + "\">" + number("en", d.UNREAD, 0) + " unread</a>", other: "There are <a href=\"" + d.unreadUrl + "\">" + number("en", d.UNREAD, 0) + " unread</a>" }) + "\n    " + plural(d.NEW, 0, en, { "0": "", one: " and <a href=\"" + d.newUrl + "\">" + number("en", d.NEW, 0) + " new</a> topic remaining,", other: " and <a href=\"" + d.newUrl + "\">" + number("en", d.NEW, 0) + " new</a> topics remaining," }) + "\n  ", false: "\n    " + plural(d.UNREAD, 0, en, { "0": "", one: "There is <a href=\"" + d.unreadUrl + "\">" + number("en", d.UNREAD, 0) + " unread</a> topic remaining,", other: "There are <a href=\"" + d.unreadUrl + "\">" + number("en", d.UNREAD, 0) + " unread</a> topics remaining," }) + "\n    " + plural(d.NEW, 0, en, { "0": "", one: "There is <a href=\"" + d.newUrl + "\">" + number("en", d.NEW, 0) + " new</a> topic remaining,", other: "There are <a href=\"" + d.newUrl + "\">" + number("en", d.NEW, 0) + " new</a> topics remaining," }) + "\n  ", other: "" }) + "\n" + select(d.HAS_CATEGORY, { true: " or browse other topics in " + d.nodeLink, false: " or <a href=\"" + d.basePath + "/latest\">view latest topics</a>", other: "" }) + "\n",
      "flagging.delete_confirm_MF": (d) => "You are about to delete " + plural(d.POSTS, 0, en, { one: "<b>" + number("en", d.POSTS, 0) + "</b> post", other: "<b>" + number("en", d.POSTS, 0) + "</b> posts" }) + " and " + plural(d.TOPICS, 0, en, { one: "<b>" + number("en", d.TOPICS, 0) + "</b> topic", other: "<b>" + number("en", d.TOPICS, 0) + "</b> topics" }) + " from this user, remove their account, block signups from their IP address <b>" + d.ip_address + "</b>, and add their email address <b>" + d.email + "</b> to a permanent block list. Are you sure this user is really a spammer?\n",
      posts_likes_MF: (d) => plural(d.count, 0, en, { one: number("en", d.count, 0) + " reply,", other: number("en", d.count, 0) + " replies," }) + select(d.ratio, { low: " high like to post ratio,", med: " very high like to post ratio,", high: " extremely high like to post ratio,", other: "" }) + " jump to the first or last post…\n",
      "chat.mention_warning.groups.too_many_members_MF": (d) => plural(d.groupCount, 0, en, { "1": "\n          " + select(d.isAdmin, { true: "\n              " + plural(d.notificationLimit, 0, en, { one: "Mentioning @" + d.group1 + " exceeds the <a href=\"" + d.siteSettingUrl + "\" target=\"_blank\">notification limit</a> of " + number("en", d.notificationLimit, 0) + " user.", other: "Mentioning @" + d.group1 + " exceeds the <a href=\"" + d.siteSettingUrl + "\" target=\"_blank\">notification limit</a> of " + number("en", d.notificationLimit, 0) + " users." }) + "\n            ", false: "\n              " + plural(d.notificationLimit, 0, en, { one: "Mentioning @" + d.group1 + " exceeds the notification limit of " + number("en", d.notificationLimit, 0) + " user.", other: "Mentioning @" + d.group1 + " exceeds the notification limit of " + number("en", d.notificationLimit, 0) + " users." }) + "\n            ", other: "" }) + "\n        ", "2": "\n          " + select(d.isAdmin, { true: "\n              " + plural(d.notificationLimit, 0, en, { one: "Mentioning @" + d.group1 + " and @" + d.group2 + " exceeds the <a href=\"" + d.siteSettingUrl + "\" target=\"_blank\">notification limit</a> of " + number("en", d.notificationLimit, 0) + " user.", other: "Mentioning @" + d.group1 + " and @" + d.group2 + " exceeds the <a href=\"" + d.siteSettingUrl + "\" target=\"_blank\">notification limit</a> of " + number("en", d.notificationLimit, 0) + " users." }) + "\n            ", false: "\n              " + plural(d.notificationLimit, 0, en, { one: "Mentioning @" + d.group1 + " and @" + d.group2 + " exceeds the notification limit of " + number("en", d.notificationLimit, 0) + " user.", other: "Mentioning @" + d.group1 + " and @" + d.group2 + " exceeds the notification limit of " + number("en", d.notificationLimit, 0) + " users." }) + "\n            ", other: "" }) + "\n        ", other: "\n          " + select(d.isAdmin, { true: "\n              " + plural(d.notificationLimit, 0, en, { one: "Mentioning these " + d.groupCount + " groups exceeds the <a href=\"" + d.siteSettingUrl + "\" target=\"_blank\">notification limit</a> of " + number("en", d.notificationLimit, 0) + " user.", other: "Mentioning these " + d.groupCount + " groups exceeds the <a href=\"" + d.siteSettingUrl + "\" target=\"_blank\">notification limit</a> of " + number("en", d.notificationLimit, 0) + " users." }) + "\n            ", false: "\n              " + plural(d.notificationLimit, 0, en, { one: "Mentioning these " + d.groupCount + " groups exceeds the notification limit of " + number("en", d.notificationLimit, 0) + " user.", other: "Mentioning these " + d.groupCount + " groups exceeds the notification limit of " + number("en", d.notificationLimit, 0) + " users." }) + "\n            ", other: "" }) + "\n        " }) + "\n",
      "chat.create_channel.auto_join_users.warning_multiple_groups_MF": (d) => plural(d.groupCount, 0, en, { one: "\n          " + plural(d.userCount, 0, en, { one: "Automatically add " + d.userCount + " user from " + d.groupName + " and " + d.groupCount + " other group?", other: "Automatically add " + d.userCount + " users from " + d.groupName + " and " + d.groupCount + " other group?" }) + "\n        ", other: "\n          " + plural(d.userCount, 0, en, { one: "Automatically add " + d.userCount + " user from " + d.groupName + " and " + d.groupCount + " other groups?", other: "Automatically add " + d.userCount + " users from " + d.groupName + " and " + d.groupCount + " other groups?" }) + "\n        " }) + "\n",
      "discourse_rewind.reports.chat_usage.message_2_MF": (d) => "You had " + plural(d.dm_count, 0, en, { one: "<strong>" + number("en", d.dm_count, 0) + "</strong> DM conversation", other: "<strong>" + number("en", d.dm_count, 0) + "</strong> DM conversations" }) + " with " + plural(d.channel_count, 0, en, { one: "<strong>" + number("en", d.channel_count, 0) + "</strong> person or group", other: "<strong>" + number("en", d.channel_count, 0) + "</strong> different people or groups" }) + ".\n",
      "admin.user.penalty_post_delete_all_confirmation_MF": (d) => "<span>This will delete\n" + plural(d.TOPICS, 0, en, { one: number("en", d.TOPICS, 0) + " topic", other: number("en", d.TOPICS, 0) + " topics" }) + " and\n" + plural(d.REPLIES, 0, en, { one: number("en", d.REPLIES, 0) + " reply", other: number("en", d.REPLIES, 0) + " replies" }) + ". <b>This cannot be undone!</b> Are you sure you would like to do this?</span>\n",
      "admin.user.penalty_history_MF": (d) => "In the past 6 months this user has been <b>suspended " + plural(d.SUSPENDED, 0, en, { one: number("en", d.SUSPENDED, 0) + " time", other: number("en", d.SUSPENDED, 0) + " times" }) + "</b> and <b>silenced " + plural(d.SILENCED, 0, en, { one: number("en", d.SILENCED, 0) + " time", other: number("en", d.SILENCED, 0) + " times" }) + "</b>.",
      "admin.user.delete_all_posts_confirm_MF": (d) => "You are about to delete " + plural(d.POSTS, 0, en, { one: number("en", d.POSTS, 0) + " post", other: number("en", d.POSTS, 0) + " posts" }) + " and " + plural(d.TOPICS, 0, en, { one: number("en", d.TOPICS, 0) + " topic", other: number("en", d.TOPICS, 0) + " topics" }) + ". Are you sure?\n"
    }
  }
}
